language: python

sudo: required

dist: trusty

env:
  - KB_SDK_BIN="kb/modules/kb_sdk/bin"

python:
  - "2.7"

install:
  - pwd
  - mkdir -p kb/modules
  - cd kb/modules
  - git clone https://github.com/kbase/kb_sdk
  - cd kb_sdk
  - echo $(pwd)
  - make bin
  - make sdkbase
  - export PATH=$(pwd)/bin:$PATH
  - cd -

script:
  - pwd
  - ./run_tests.sh &> debug.txt
  - coverage report --skip-covered

after_success:
  - codecov -f test_local/workdir/.coverage

after_failure:
  - cat debug.txt