language: python

sudo: required

dist: trusty

env:
  - KB_SDK_BIN="kb/modules/kb_sdk/bin"

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
  - sudo apt-get update
  - sudo apt-get install linux-image-extra-$(uname -r)
  - sudo apt-get install linux-image-generic-lts-trusty
  - sudo apt-get install docker-engine
  - sudo service docker start

install:
  - pwd
  - mkdir -p kb/modules
  - cd kb/modules
  - git clone https://github.com/kbase/kb_sdk
  - cd kb_sdk
  - echo $(pwd)
  - make bin
  - make sdkbase
  - export PATH=$(pwd)/bin:$PATH
  - cd -

script:
  - ./run_tests.sh &> test_local/debug.txt
  - coverage report --skip-covered

after_success:
  - codecov -f test_local/workdir/.coverage

after_failure:
  - cat test_local/debug.txt